apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
