name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: collector
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Ruff
        working-directory: collector
        run: ruff check
      - name: Mypy
        working-directory: collector
        run: mypy
      - name: Pytest
        working-directory: collector
        run: pytest
      - name: Validate docker compose
        run: docker compose config
