name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guard: no Prometheus references
        run: |
          if git ls-files | xargs grep -nEi 'prometheus|collector:9333|(^|[^a-z])\\/metrics([^a-z]|$)'; then
            echo "Prometheus references are not allowed in this repo."; exit 1;
          fi
      - name: Guard: no wrapper dir
        run: |
          if [ -d "bitcoin-monitoring-stack" ]; then
            echo "Do not nest the project under bitcoin-monitoring-stack/"; exit 1;
          fi
      - name: Guard: no binaries
        run: |
          bad=$(git ls-files | xargs file -i | grep -v 'charset=utf-8' || true)
          if [ -n "$bad" ]; then
            echo "$bad"; echo "Binary files are not allowed."; exit 1;
          fi
      - name: Prepare env file
        run: cp .env.example .env
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: collector
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Ruff
        working-directory: collector
        run: ruff check
      - name: Mypy
        working-directory: collector
        run: mypy --config-file ../mypy.ini
      - name: Pytest
        working-directory: collector
        run: pytest
      - name: Validate docker compose
        run: |
          ENV_FILE_PATH=.env.example docker compose config
