name: CI

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./collector[dev]
      - name: Ruff
        run: ruff check collector

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./collector[dev]
      - name: MyPy
        run: mypy --config-file mypy.ini collector/collector

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./collector[dev]
      - name: Pytest
        working-directory: collector
        run: pytest

  compose:
    runs-on: ubuntu-latest
    env:
      INFLUX_SETUP_USERNAME: test
      INFLUX_SETUP_PASSWORD: test
      ENV_FILE_PATH: .env.example
    steps:
      - uses: actions/checkout@v4
      - name: Validate docker compose
        run: docker compose config

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
